### PR TITLE
Mobile Projection

### PR DESCRIPTION
**Pull request by yang1070**
The aim of the Mobile Projection feature is to allow application developers to create custom application use experiences that are not limited by HMI templates. Mobile Projection applications will be able to stream a video feed to the system and allow users to interact with the application by touching the system's screen.

Please review this pull request.

### CODE REVIEW

**Comment by joeljfischer** [comment]
Hi @yang1070, what is the difference between this and #57?

Also, please update your title and description, the title for the PR must be the same as your proposal, and the description of the PR must be the same as your introduction.

**Comment by yang1070** [comment]
@joeljfischer Sorry, I'm not aware that there is already a proposal for the mobile projection. The difference between this one and #57, is that this version does not contains the full screen mode.

**Comment by joeljfischer** [comment]
@yang1070 I would like to close one or the other of the PRs, since they appear nearly identical. Which would you prefer to have closed?

Also, so that you know, if you wish for a PR to go into review, you must explicitly ask for it on the pull request.

**Comment by yang1070** [comment]
@joeljfischer Please close #57.

**Comment by shengbi** [comment]
I would very much like to see this supported in some way!

**Pull request merged**
