### PR TITLE
NNNN-use-boost-library_technical-part

### PR DESCRIPTION
**Pull request by DrachenkoAnastasiia**
This proposal is the technical continuation for the proposal [#44](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0044-use-Boost-library.md). It supposed to demonstrate in practice the Boost library advantages over the hand-written algorithms.

[In creating a Pull Request for SDL Evolution, please note the following guidelines:
1. Please make the title of your pull request the *exact* title of your proposal.
2. Please make the text of your pull request the *exact* text of the introduction of your proposal.
3. Please make a new comment (do not do this in the initial text) notifying @theresalech that the proposal is ready for review when you wish to make no more changes and for the SDLC Steering Committee to consider reviewing your pull request. It will not be considered for review until you have done so.
4. Please follow the [template](https://github.com/smartdevicelink/sdl_evolution/blob/master/0000-template.md) and fill out the metadata at the top properly.
5. Please make sure your proposal is clear for reviewers to read, keeping in mind that the majority of reviewers are English-speaking. Proposals should be formatted per the templates and guidelines provided, including the rules in (4). Once you have asked for a "review ready" tag, the project maintainers will quickly skim your proposal and note obvious errors that need to be fixed. The maintainers are not to be relied upon to catch all errors. The Steering Committee may push back on misformatted proposals or decide not to review a proposal until it is formatted properly and easily read. Please make sure your proposals are in a "final" state before requesting review!

Please delete the above section when you have read it.]

### CODE REVIEW

**Comment by AGaliuzov** [comment]
@theresalech please consider this one as ready for review. This is addition to the #133

**Comment by joeljfischer** [comment]
@AGaliuzov This is not ready for review, please read and followed the guidelines listed.

**Comment by AGaliuzov** [comment]
@joeljfischer I made this proposal as the addition to the existing one. Do I need to write again all these items as motivation, downside etc?

**Comment by theresalech** [comment]
@DrachenkoAnastasiia or @AGaliuzov can you please close this PR, as #154 has been entered and merged in place of this one?

**Comment by DrachenkoAnastasiia** [comment]
According to the letter from @theresalech

**Pull request closed without merging**
