### PR TITLE
Move to the new C++11 standard

### PR DESCRIPTION
**Pull request by AGaliuzov**
This proposal is geared to upgrade currently used `C++98` standard to `C++11` as the latter one has much more useful features and significant improvements from the performance point of view. Also it became more safe in runtime and allows to catch a lot of issues during the compilation stage.

### CODE REVIEW

**Comment by joeljfischer** [comment]
@AGaliuzov Your proposal title is misspelled. Your PR title should match the proposal title and the text should match your proposal introduction.

**Comment by joeljfischer** [comment]
@AGaliuzov Additionally, your proposal introduction should introduce the proposal, not give a history of C++ and in car systems.

**Comment by AGaliuzov** [comment]
@joeljfischer thank you. I will consider next time.

**Comment by AGaliuzov** [comment]
@joeljfischer please consider this one as review ready

**Comment by joeljfischer** [comment]
@AGaliuzov Your title has spelling errors, you altered the PR title to not match your proposal title, and your introduction has line breaks when there shouldn't be line breaks.

**Comment by AGaliuzov** [comment]
@joeljfischer I have remove the line breaks and fix spelling in description

**Comment by AGaliuzov** [comment]
@joeljfischer I've changed the title.

**Pull request merged**
