### PR TITLE
Communication app activation during active embedded audio source or navigation

### PR DESCRIPTION
**Pull request by KhrystynaDubovyk**
Index on Communication app activation during active embedded audio source or navigation was added.

### CODE REVIEW

**Comment by KhrystynaDubovyk** [comment]
@LuxoftAKutsan, @mghiumiusliu, @tmelnyk, @drachenkoanastasiia
please review

**Comment by asm09fsu** [comment]
@KhrystynaDubovyk this needs to be updated to have a more readable name (don't just put the file name).

**Comment by KhrystynaDubovyk** [comment]
hello, @asm09fsu 
could you please specify how I can rename this? is this name meaningless?
> don't just put the file name
what is appropriate to put instead?

**Comment by joeljfischer** [comment]
The title of the PR should be the title of the evolution proposal. In this case: "Communication app activation during active embedded audio source or navigation"

**Comment by KhrystynaDubovyk** [comment]
@ joeljfischer 
should the name of the PR and the title of the evolution proposal be the same?
**ProTip!** says:

> Great commit summaries contain fewer than 50 characters. Place extra information in the extended description 

In this case, shall I rename the title of the evolution proposal to 'Communication app activation'?

**Comment by joeljfischer** [comment]
No, just make the entire name of the PR the same as the title of the evolution proposal. You can ignore the tip.

**Comment by TMelnyk** [comment]
1. Agree with Joe regarding naming
2. This proposal is to provide communication app activation during active embedded sources.
This proposal is to **handle** communication app activation during active **embedded audio and navigation sources.**
3. Motivation  - it is not covered cases actually
But if we`ll rework it - left w/o changes
4. Could you please add some numeric list (1 2 3) to each req at proposed solution
5. Please also add lable or status or smth -  "under_clarification"

**Comment by TMelnyk** [comment]
reviewed

**Comment by AGaliuzov** [comment]
@joeljfischer this one is ready for review

**Pull request merged**
