### PR TITLE
Update to SDL0211 - Service Status Update to HMI

### PR DESCRIPTION
**Pull request by yang1070**
# Introduction

First, there is a name confliction on the enumeration of `ServiceUpdateReason` in approved proposals [App Services](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0167-app-services.md) and [ServiceStatusUpdateToHMI](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0211-ServiceStatusUpdateToHMI.md).

Second, in the [ServiceStatusUpdateToHMI](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0211-ServiceStatusUpdateToHMI.md) proposal, it defines 3 possible service update reasons (`PTU_FAILED`, `INVALID_CERT`, `INVALID_TIME`) when a `StartService` request is rejected. During the implementation, we identified more cases that need a reason:
- When a service is rejected because the system configuration ini file requires the enforcement of a protected service, but the app requests for an unprotected service.
- When a mobile app requests a protected service, but the system starts an unprotected service instead.

# Motivation
To resolve name conflict and add more update reasons.

# Proposed solution

Rename `ServiceUpdateReason` to `ServiceStatusUpdateReason` as App services also uses the same name `ServiceUpdateReason`.
Add two new reason codes to the enumeration of `ServiceStatusUpdateReason`.

The following are changes to the HMI_API.xml.

```xml

<function name="OnServiceUpdate" messagetype="notification">
    :
-   <param name="reason" type="Common.ServiceUpdateReason" mandatory="false">
+   <param name="reason" type="Common.ServiceStatusUpdateReason" mandatory="false">
    :
</function>

-<enum name="ServiceUpdateReason">
+<enum name="ServiceStatusUpdateReason">
    :
    :
    <element name="PROTECTION_ENFORCED" >
      <description>When a Service is rejected because the system configuration ini file requires the service must be protected, but the app asks for an unprotected service.</description>
    </element>
    <element name="PROTECTION_DISABLED" >
      <description>When a mobile app requests a protected service, but the system starts an unprotected service instead.</description>
    </element>
</enum>

```

# Potential downsides
N/A

# Impact on existing code

- Requires changes on SDL core and HMI_API.
- Does not require a version change as it is not a released feature.

# Alternatives considered
No alternatives were considered by the author.

### CODE REVIEW

**Comment by yang1070** [comment]
@theresalech this PR is ready for review. thanks.

**Comment by yang1070** [comment]
@jordynmackoo This  PR is ready for review. We would like to get it ready for today's SDLC meeting. Thank you.

**Comment by theresalech** [comment]
@yang1070 as this is a requested change to an accepted, but not yet implemented proposal, please submit a PR following a format similar to this one: https://github.com/smartdevicelink/sdl_evolution/pull/605.  The introduction, motivation, etc. for the proposal should be included in the PR description, and the PR should be to make changes to the accepted proposal (https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0211-ServiceStatusUpdateToHMI.md).  Please let me know if you have any questions, thanks!

**Comment by yang1070** [comment]
@theresalech  I update the PR using the suggested format. Now it ready for review. thanks,

**Pull request merged**
