### PR TITLE
"ClimateControlData" structure changes in Mobile and HMI APIs

### PR DESCRIPTION
**Pull request by OlesiaV**
"ClimateControlData" structure defines the available remote-control options of the "CLIMATE" vehicle module for remote-control mobile application.

### CODE REVIEW

**Comment by OlesiaV** [comment]
@joeljfischer please consider this proposal as ready for review

**Comment by theresalech** [comment]
@OlesiaV you can tag me in proposals when you need the "review ready" label added.  This one is all set.  Thanks!

**Comment by theresalech** [comment]
This proposal is dependent on the implementation of the Remote Control feature.  Once that feature has been implemented, this proposal can be reviewed by the Steering Committee.

**Comment by yang1070** [comment]
@OlesiaV  Please close or cancel this PR, as the proposed change is in the RC baseline proposal already.

**Comment by OlesiaV** [comment]
Closed as not actual

**Pull request closed without merging**
