### PR TITLE
SDL must respond OnAppInterfaceUnregistered (PROTOCOL_VIOLATION) in case mobile app sends malformed messages

### PR DESCRIPTION
**Pull request by KhrystynaDubovyk**
The index was added.

### CODE REVIEW

**Comment by KhrystynaDubovyk** [comment]
@mghiumiusliu, @tmelnyk, @drachenkoanastasiia
Please review

**Comment by asm09fsu** [comment]
@KhrystynaDubovyk this needs to be updated to have a more readable name (don't just put the file name).

**Comment by TMelnyk** [comment]
1. Required additional clarification from FORD
PLease remove
2. Please add numeric list (1 2 3) for each req to Proposed solution

**Comment by joeljfischer** [comment]
@KhrystynaDubovyk @theresalech This has been sitting here for months, can it be closed or marked ready?

**Comment by TMelnyk** [comment]
@KhrystynaDubovyk , please close this PR

**Pull request closed without merging**
