### PR TITLE
Accepted Revision SDL-0293 Enable OEM exclusive apps support

### PR DESCRIPTION
**Pull request by LitvinenkoIra**
Updates to reflect the Steering Committee agreed-upon revisions in [this comment ](https://github.com/smartdevicelink/sdl_evolution/issues/1108#issuecomment-768409689)

### CODE REVIEW

**Comment by LitvinenkoIra** [comment]
@mrapitis please review

**Comment by jordynmackool** [comment]
@LitvinenkoIra prior to tagging Livio to review, please add yourself as an author to the proposal.

**Comment by mrapitis** [comment]
@LitvinenkoIra changes approved from the Ford side.

**Comment by LitvinenkoIra** [comment]
@pelsila This PR is ready for review. Thank you!

**Review by pelsila — APPROVED** [review]

**Comment by vladmu** [comment]
@pelsila @mrapitis @LitvinenkoIra @AKalinich-Luxoft I have point regarding proposed changes because I see some data inconsistency in the way proposed here. `systemHardwareVersion` looks very similar to `systemSoftwareVersion`which was not placed in `VehicleType` but is a separate parameter in `RegisterAppInterfaceResponse` and `GetSystemInfo` function. So my concern is that in the proposed revision `systemHardwareVersion` is a part of `VehicleType` and not implemented in the same way as `systemSoftwareVersion`.

**Comment by jordynmackool** [comment]
@vladmu can you please post your feedback on the newly created review issue here: https://github.com/smartdevicelink/sdl_evolution/issues/1108

**Comment by jordynmackool** [comment]
@LitvinenkoIra please let me know when this PR has been updated to reflect the Steering Committee agreed-upon revisions in [this comment ](https://github.com/smartdevicelink/sdl_evolution/issues/1108#issuecomment-768409689). Thanks!

**Comment by LitvinenkoIra** [comment]
@jordynmackool PR is ready for review. Please check 22d9777 and 0ccbbca 
Thank you!

**Review by jordynmackool — APPROVED** [review]

**Pull request merged**
