### PR TITLE
Improve Automated test framework

### PR DESCRIPTION
**Pull request by LuxoftAKutsan**
The proposal is to resolve current ATF boundaries and make ATF more flexible, salable. 
Additional point is seamless integration with CI systems.
As plus there are further possibilities to provide performance testing and scenario testing

### CODE REVIEW

**Comment by AGaliuzov** [comment]
@joeljfischer this one is ready for review

**Comment by joeljfischer** [comment]
@joeygrover @theresalech what do we want to do about PRs that add images such as this one? Should they add these assets directly to this repository? What about the gitignore this PR adds?

**Comment by joeljfischer** [comment]
Hi @AGaliuzov, until we decide on the questions noted in my last comment, I cannot mark this as ready.

**Comment by joeljfischer** [comment]
@AGaliuzov @LuxoftAKutsan I have fixed it for this PR, but note that PR titles must match the proposal title and the PR text must match the proposal introduction.

**Comment by AGaliuzov** [comment]
@joeljfischer clear, thanks a lot

**Comment by AGaliuzov** [comment]
@joeljfischer  thank you. We will check this in all our proposals

**Comment by joeljfischer** [comment]
@LuxoftAKutsan @theresalech This has been sitting here for months, can it be closed or marked ready?

**Comment by AGaliuzov** [comment]
@joeljfischer Let me, please, check the current status with the team.

**Comment by theresalech** [comment]
@AGaliuzov any update from the team?

**Pull request closed without merging**
