### PR TITLE
Revise 0315 - Add RPC conflict management

### PR DESCRIPTION
**Pull request by Akihiro-Miyazaki**
## Introduction
This is an update of SDL-0315.

## Motivation
1. Remove "For instance, ONS and TTS conflicts are managed by prioritizing the latter RPC.".
2. Change the word from "middleware" to "HMI"  according to [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/1068#issuecomment-744983593).

## Proposed solution
1. Add the ON/OFF switch feature of RPC Conflict Management function.
2. Remove references to SubtleAlert from tables and other comments about implementation and add the below sentence to the "Proposed solution" section of the proposal:

Because SubtleAlert is designed to work alongside other ONS RPCs, it is exempted from this proposal and will be sent to the HMI alongside any other ONS RPC. It will be up to the HMI to determine if the SubtleAlert contains TTS data and whether or not to play that TTS data alongside showing the SubtleAlert UI based on whether other TTS data is currently playing from another RPC.

## Potential downsides
Modify the "Potential downsides" section in the proposal to include the below sentences:

Enabling this feature will force only one modal RPC to ever be displayed for every OEM implementing SDL. As a result, the system can not support multi ON-screen(ONS) and text-to-speech(TTS) RPCs notification.
However, by using the parameter of UseCoreRpcConflictManagement set to Disable, SDL Core can continue to pass through ONS and TTS RPCs to the HMI as happens now.

### CODE REVIEW

**Comment by Akihiro-Miyazaki** [comment]
Hi, @pelsila -san,
Thank you for your cooperation as always.
We finished to update the proposal documentation and image files.
We made a commit them.
Could you please confirm them.
Thank you.

**Review by jordynmackool — CHANGES_REQUESTED** [review]
Hi @Akihiro-Miyazaki, I've completed my review. Please let me know if you have any questions or concerns addressing my feedback. Thank you!

**Comment by Akihiro-Miyazaki** [comment]
Hi, @jordynmackool -san,
Thank you for your suggestion as always.
I have no question about your suggestion.
Therefore, I made a commit them.
Thank you.

**Review by jordynmackool — APPROVED** [review]

**Comment by jordynmackool** [comment]
Based on the overall requested changes the below sentence needed to be updated to align with the agreed-upon revisions. 

**This sentence:** However, by using the parameter of UseCoreRpcConflictManagement set to Disable, SDL Core can continue to pass through ONS and TTS RPCs to the HMI as happens now. 

**Now reads as:** However, by using the parameter of `EnableRPCConflictManager` set to false, SDL Core can continue to pass through ONS and TTS RPCs to the HMI as happens now.

**Pull request merged**
