### PR TITLE
ChangeRegistration-Manager

### PR DESCRIPTION
**Pull request by acerati1**
ChangeRegistration RPC allows an app to manipulate parameters that were sent during app registration including app name, TTS name and voice synonyms of the app. This proposal aims to make it more convenient for the app developer to change the apps registration and to provide an API which fits to the design of the application lifecycle manager.

### CODE REVIEW

**Comment by acerati1** [comment]
This is the review of #153. 

@theresalech PR is ready for review

**Comment by joeljfischer** [comment]
@acerati1 Why was #153 closed and this opened? You should have just been able to update #153. We lose continuity and it's confusing when a PR is closed, and the exact same thing is re-opened.

**Comment by acerati1** [comment]
@joeljfischer I had to open a new one as I created it in the wrong branch in the first place. This was preventing me to create further pull requests correctly.

**Comment by theresalech** [comment]
@acerati1 I've marked this as "review ready."  However, in the future, please revise your proposals based on the comments left in an initial review instead of creating a new PR.

**Pull request merged**
