### PR TITLE
Malformed packet: length of search for the next valid header must be limited by .ini file settings

### PR DESCRIPTION
**Pull request by KhrystynaDubovyk**
Index was added.

### CODE REVIEW

**Comment by KhrystynaDubovyk** [comment]
@mghiumiusliu, @tmelnyk, @sia_drachenko 
please review

**Comment by asm09fsu** [comment]
@KhrystynaDubovyk this needs to be updated to have a more readable name (don't just put the file name).

**Comment by TMelnyk** [comment]
1. Required additional clarification from FORD
Please remove it

**Comment by LuxoftAKutsan** [comment]
Reworked this PR:
https://github.com/smartdevicelink/sdl_evolution/pull/130
@TMelnyk @asm09fsu  @KhrystynaDubovyk  please review

**Comment by joeljfischer** [comment]
@KhrystynaDubovyk @theresalech This has been sitting here for months, can it be closed or marked ready? Also, seems to be the same as #130?

**Pull request closed without merging**
