### PR TITLE
Mobile API versioning revision

### PR DESCRIPTION
**Pull request by kshala-ford**
The proposal to add versioning to the mobile API was accepted with the revision to use the maintainer’s proposal. The suggested code will solve the same problem, while making parsing easier. The suggested code is 

```xml
<enum name="ButtonName">
</element>
  <element name="OK" mandatory="false" deleted="4.6.0">
    <description>
      The button name for the physical OK button.
      It is not related to the Play/Pause button.
      Please use the physical `PLAY_PAUSE` button.
    </description>
    <previousVersions>
      <element name="OK" mandatory="true" since="1.0.0" removed="4.5.0"/>
      <element name="OK" mandatory="false" since="4.5.0" deprecated="4.5.2"/>
      <element name="OK" mandatory="false" deprecated="4.5.2" removed="4.6.0"/>
    </previousVersions>     
  </element>
</enum>
```

With the following comment

> I think this is much more confusing and difficult to write a parser for than the maintainer suggestion above. The maintainer suggestion provides only two version parameters: from and until (though these could be different, such as since). Then, all the other parameters become booleans, including deprecated and removed or deleted (whichever wording is chosen). To me, this seems easy to read and easy to parse. In particular, the mandatory change in the revised version seems very confusing.

This document will show scenarios for the mobile API and how to solve them using the author’s proposal and the maintainer’s proposal. At the end both proposals will be compared:

-	What’s the increase the mobile API?
-	What’s the complexity to read the mobile API as a human?
-	What’s the complexity to read the mobile API as a parser?

To compare the parser complexity the comparison includes xpaths to locate the relevant information including versioning.

### CODE REVIEW

**Comment by kshala-ford** [comment]
@theresalech PR ready for review.

**Comment by LuxoftAKutsan** [comment]
@kshala-ford this proposal is about integrating into MOBILE API structure version control system for each element. 
Not sure that is would be rely useful. As for me changing in API's is major changes and should be listed in release notes.

**Comment by kshala-ford** [comment]
@LuxoftAKutsan actually this proposal is already accepted (see #269) and allows to store versioning metadata in a structured way. Once this information is available it's planned to use that metadata for various reasons e.g. to avoid version clashes between app and head unit. This will be done in future proposals.

**Comment by jacobkeeler** [comment]
@kshala-ford Sorry if I'm misunderstanding, but as far as I can tell, the proposed solution by the maintainer is:

```xml
<enum name="ButtonName">
  <element name="OK" mandatory="false" deleted="true" from="4.6.0">
    <description>
      The button name for the physical OK button.
      It is not related to the Play/Pause button.
      Please use the physical `PLAY_PAUSE` button.
    </description>
    <previousVersions>
      <element name="OK" mandatory="true" from="1.0.0" until="4.5.0"/>
      <element name="OK" mandatory="false" from="4.5.0" until="4.5.2"/>
      <element name="OK" mandatory="false" deprecated="true" from="4.5.2" until="4.6.0"/>
    </previousVersions>     
  </element>
</enum>
```

Rather than:
```xml
<enum name="ButtonName">
  <element name="OK" mandatory="false" deleted="4.6.0">
    <description>
      The button name for the physical OK button.
      It is not related to the Play/Pause button.
      Please use the physical `PLAY_PAUSE` button.
    </description>
    <previousVersions>
      <element name="OK" mandatory="true" since="1.0.0" removed="4.5.0"/>
      <element name="OK" mandatory="false" since="4.5.0" deprecated="4.5.2"/>
      <element name="OK" mandatory="false" deprecated="4.5.2" removed="4.6.0"/>
    </previousVersions>     
  </element>
</enum>
```

The latter was just a potential solution proposed by Joel, which was later revised. The revised version of this format was the accepted format.

The most recent version of an element is in it's base tag, and the entire state of that element is copied whenever a revision is made (resulting in a new entry in `previousVersions`). A range of versions (`from=... until=...`) is also included to show when that version of the tag was used. In this case, the state of the tag is kept with each revision, rather than just the changes since the previous version (as is the case with your proposed solution).

This solution makes it very easy to target old versions of the spec, and is very easy to parse. The parser can just use the copy of the element/parameter that is tied to the targeted RPC Spec version. It is certainly on the verbose side, however.

Based on the format which was accepted, the maintainer's proposal for Scenario 1 would be:
```xml
 <struct name="SyncMsgVersion">
   <description>Specifies the version number of the SYNC V4 protocol, that is supported by the mobile application</description>
   <param name="majorVersion" type="Integer" minvalue="1" maxvalue="10" />
   <param name="minorVersion" type="Integer" minvalue="0" maxvalue="1000" />
   <param name="patchVersion" type="Integer" minvalue="0" maxvalue="1000" mandatory="false" deleted="true" from="5.0.0">
     <previousVersions>
       <param name="patchVersion" type="Integer" minvalue="0" maxvalue="1000" mandatory="false" from="4.4.0" until="4.5.0">
       <param name="patchVersion" type="Integer" minvalue="0" maxvalue="1000" mandatory="false" deprecated="true"  from="4.5.0" until="5.0.0" />
     </previousVersions>
   </param>
 </struct>
```

Scenario 2:
```xml
 <struct name="SyncMsgVersion" deleted="true" from="6.0.0">
   <description>Specifies the version number of the SYNC V4 protocol, that is supported by the mobile application</description>
   <param name="majorVersion" type="Integer" minvalue="1" maxvalue="10" />
   <param name="minorVersion" type="Integer" minvalue="0" maxvalue="1000" />
   <param name="patchVersion" type="Integer" minvalue="0" maxvalue="1000" mandatory="false" deleted="true" from="5.0.0">
     <previousVersions>
       <param name="patchVersion" type="Integer" minvalue="0" maxvalue="1000" mandatory="false" from="4.4.0" until="4.5.0">
       <param name="patchVersion" type="Integer" minvalue="0" maxvalue="1000" mandatory="false" deprecated="true" from="4.5.0" until="5.0.0" />
     </previousVersions>
   </param>
   <previousVersions>
     <struct name="SyncMsgVersion" from="1.0.0" until="5.0.0" />
     <struct name="SyncMsgVersion" deprecated="true" from="5.0.0" until="6.0.0" />
   </previousVersions>
 </struct>
 
 <struct name="MsgVersion" from="5.0.0">
   <param name="majorVersion" type="Integer" minvalue="1" maxvalue="10" />
   <param name="minorVersion" type="Integer" minvalue="0" maxvalue="1000" />
 </struct>
```

Scenario 3:
```xml
<struct name="MsgVersion" from="5.0.0">
  <param name="majorVersion" type="Integer" minvalue="1" maxvalue="100" from="5.1.0">
    <previousVersions>
      <param name="majorVersion" type="Integer" minvalue="1" maxvalue="10" from="5.0.0" until="5.1.0" />
    </previousVersions>
  <param name="minorVersion" type="Integer" minvalue="0" maxvalue="1000" />
</struct>
```

Scenario 4:
```xml
<struct name="MsgVersion" from="5.0.0">
  <param name="majorVersion" type="Integer" minvalue="1" maxvalue="100" deleted="true" from="6.0.0">
    <previousVersions>
      <param name="majorVersion" type="Integer" minvalue="1" maxvalue="10" from="5.0.0" until="5.1.0" />
      <param name="majorVersion" type="Integer" minvalue="1" maxvalue="100" from="5.1.0" until="5.2.0" />
      <param name="majorVersion" type="Integer" minvalue="1" maxvalue="100" deprecated="true"  from="5.2.0" until="6.0.0" />
    </previousVersions>
  </param>
  <param name="minorVersion" type="Integer" minvalue="0" maxvalue="1000" />
</struct>
```

**Comment by joeljfischer** [comment]
@jacobkeeler Thanks for listing this out! It appears correct to me, what you posted is what was accepted rather than the listing within this PR. The only scenario I can see being confusing for human readership is scenario 2 (though once you understand the structure, I think it's not too bad), but considering that the parsing is very easy due to just finding the version it is within in the `from` and `until` tags, while the rest are simple booleans. The only possible change I could see being useful is to, instead of `previousVersions` being from oldest to newest, making it newest to oldest, because the current version is the newest. I believe that the original proposal is still best.

**Comment by kshala-ford** [comment]
I've modified the file based on the comment above. The maintainer's proposal should now match.

Different to your opinion I honestly don't see any advantage to the original proposal. The footprint is so much higher and it requires much more changes for the parser. The authors proposal only adds a minimum footprint by using a single attribute. It cannot be made more easy for humans and parsers to read those changes.

**Comment by kshala-ford** [comment]
Hi @theresalech @joeljfischer @joeygrover , jut wanted to let you know that I updated the PR. I deleted my revision.md file and updated the original file to match what we agreed on. The versioning proposal should be ready now.

**Pull request merged**
