### PR TITLE
Support for Multiple Proxy Managers #771

### PR DESCRIPTION
**Pull request by yoooriii**
The ability to use multiple Sdl Proxy Managers to spin up and represent multiple SDL apps on the vehicle head unit for any given single mobile application.

### CODE REVIEW

**Comment by Kazuki-Sugimoto** [comment]
Hi @yoooriii -san

After discussing our proposal (#892), your PR was suggested.
We agree with this proposal.
Could you tell us the status of this PR?

**Comment by Kazuki-Sugimoto** [comment]
@theresalech -san
I would like to contact the proposer, so please support me.

**Comment by theresalech** [comment]
Hi @Kazuki-Sugimoto -san, I have provided contact information to Kawano-san via email.

**Comment by jordynmackool** [comment]
@yoooriii can you please provide a status on this PR as it has been inactive for some time?

**Comment by jordynmackool** [comment]
Closing as inactive. Should the author wish to bring this PR under Steering Committee review, the author should notify the Project Maintainer (via admin@smartdevicelink.com), and then the PR can be re-opened.

**Pull request closed without merging**
