### PR TITLE
NNNN-OnAppRegistered_providing_AppIcon_of_app_registration.md; NNNN-RegisterAppInterface_steeringWheelLocation_parameter.md; NNNN-SetAudioStreamingIndicator_conditions_to_handle_related_cases.md

### PR DESCRIPTION
**Pull request by DrachenkoAnastasiia**
Add the proposal to provide the applivations icon in case of app registration.

### CODE REVIEW

**Comment by DrachenkoAnastasiia** [comment]
please, review
@mghiumiusliu, @tmelnyk, @KhrystynaDubovyk

**Comment by DrachenkoAnastasiia** [comment]
please, review
@mghiumiusliu, @tmelnyk, @KhrystynaDubovyk

**Comment by asm09fsu** [comment]
@DrachenkoAnastasiia  this needs to be updated to have a more readable name (don't just put the file name).

**Comment by joeljfischer** [comment]
Hello @DrachenkoAnastasiia, we require only one proposal per PR.

**Comment by TMelnyk** [comment]
1. Agree with Joe - please split to 3 PR
2. This proposal is to provide the **applivations _icon_** to HMI in case of app registration. 
Please re-check
3. **Required additional clarification from FORD.**
PLease remove
4. Why you didn`t add functional req-s from CRQ to this PR?

**Comment by TMelnyk** [comment]
RegisterAppInterface:

1. Required additional clarification from FORD
PLease remove it
2. Why you didn`t add functional req-s from CRQ to this PR?

**Comment by TMelnyk** [comment]
SetAudioStreamingIndicator
1. Required additional clarification from FORD
Please remove it
2. Why you didn`t add functional req-s from CRQ to this PR?
You just copied HMI behavior, not SDL

**Comment by DrachenkoAnastasiia** [comment]
Tanya, kindly note that this PR is closed.

**Comment by TMelnyk** [comment]
Oooops :)

**Pull request closed without merging**
