### PR TITLE
Remote Control HMI Settings

### PR DESCRIPTION
**Pull request by acerati1**
SDL remote control provides the ability for mobile applications to control certain components of the vehicle, such as, tune the radio, set the desired temperature or change the fan speed

### CODE REVIEW

**Comment by acerati1** [comment]
@theresalech ready to be reviewed

**Comment by joeygrover** [comment]
This proposal hinges upon a high level remote control proposal being submitted. It will not be reviewed until that proposal is brought to the committee.

**Comment by joeygrover** [comment]
Also this functionality is already included in #121. Please review previously submitted PRs from your organizations before submitting new ones. These actions are cluttering up this repo.

**Comment by yang1070** [comment]
@acerati1 @theresalech Could any of you please cancel/close this PR? As I have no access right to update it to accommodate the changes in remote control baseline. I would like to start a new PR.

**Pull request closed without merging**
