### PR TITLE
Providing AppIcon in case of app registration

### PR DESCRIPTION
**Pull request by DrachenkoAnastasiia**

### CODE REVIEW

**Comment by DrachenkoAnastasiia** [comment]
please review
@tmelnyk
@mghiumiusliu 
@KhrystynaDubovyk

**Comment by TMelnyk** [comment]
1. Required additional clarification from FORD.
PLease remove
2. Why you didn`t add functional req-s from CRQ to this PR?

**Comment by JackLivio** [comment]
@TMelnyk What CRQ is this evolution item tied to?

**Comment by TMelnyk** [comment]
@JackLivio , as I can see we didn`t add this CRQ to github yet
If you need more details about this changes - I can provide short description and diagrams
@mghiumiusliu, please clarify when this CRQ will be posted at github?
Thank you in advance!

**Comment by mfoedisch** [comment]
I'm a bit confused about the issue that is meant to get fixed here. Is it to avoid additional transport chatter? Is it to have an icon available instantaneously with registration? ...?

Could any of the existing mechanism be used, e.g. resumption or file handling? Or could this even be considered an HMI-specific behavior and kept out of the protocol?

**Comment by TMelnyk** [comment]
Hello @mfoedisch 
Let me describe the use case for this:

app -> SDL: PutFile (<Image_123>)
SDL stores this <Image_123> to <AppStorageFolder>
SDL -> app: PutFile (SUCCESS)
SDL -> HMI: OnPutFile ( )

User chooses <Image_123> as apps icon

app -> SDL: SetAppIcon (<Image_123>)
SDL -> HMI: UI.SetAppIcon (<Image_123>)
HMI -> UI.SetAppIcon (SUCCESS)
SDL -> app: SetAppIcon (SUCCESS)

HMI set <Image_123> as appIcon
SDL copies this <Image_123> to <AppIconsFolder>

IGN ON - IGN OFF
app -> SDL: RegisterAppInterface()

ICON EXISTS
SDL checks whether this app has icon -> it has _(stored at <AppIconsFolder>)_
SDL -> app: RegisterAppInterface (**iconResumed: true**)
SDL -> HMI: OnAppRegistered (<Icon_123>)
HMI displays app with icon <Image_123>

ICON DOES NOT EXIST
SDL checks whether this app has icon -> NO icon
SDL -> app: RegisterAppInterface (**iconResumed: false**)
SDL -> HMI: OnAppRegistered ( )
HMI displays app without icon and User can upload and/or choose new icon

Please return in case you have more questions

**Comment by mrapitis** [comment]
@DrachenkoAnastasiia @TMelnyk Can we please close this pr in favor of the pr below?

https://github.com/smartdevicelink/sdl_evolution/pull/114

**Comment by TMelnyk** [comment]
@DrachenkoAnastasiia , please close this PR

**Pull request closed without merging**
