### PR TITLE
Respond to backslash symbol at "fileName" parameter

### PR DESCRIPTION
**Pull request by KhrystynaDubovyk**
Index was added.

### CODE REVIEW

**Comment by KhrystynaDubovyk** [comment]
@mghiumiusliu, @tmelnyk, @sia_drachenko
please review

**Comment by asm09fsu** [comment]
@KhrystynaDubovyk this needs to be updated to have a more readable name (don't just put the file name).

**Comment by TMelnyk** [comment]
1. Respond to backslash symbol at "fileName" parameter
Please change to - Invalidate PutFile due to "fileName" with backslash
2. Introduction
IS not clear at all
Please re-phrase - SDL must invalidate PutFile requets from apps dur to "fileName" with backslash
3. Required additional clarification from FORD
Please remove

**Comment by JackLivio** [comment]
Related PR https://github.com/smartdevicelink/sdl_core/pull/1043

**Comment by LuxoftAKutsan** [comment]
@KhrystynaDubovyk please close this pull request.
@JackLivio  @TMelnyk @asm09fsu 
This one if update https://github.com/smartdevicelink/sdl_evolution/pull/129

**Pull request closed without merging**
