### PR TITLE
Add video streaming capabilities

### PR DESCRIPTION
**Pull request by jhludwig**
This proposal provides a video streaming capability information to SDL apps. This is achieved by HMI notification of video capabilities to SDL core and proxy.

### CODE REVIEW

**Comment by jhludwig** [comment]
@theresalech modifications to respond to channel discussion.  ready for review

**Comment by theresalech** [comment]
@jhludwig as the original proposal (#176) is currently in review, we'll need to bring it to a vote among Steering Committee representatives in our meeting today (2017-05-16).  If the majority of members agree to revise the proposal based on the current review comments, the proposal will be returned for revisions and we can then merge these changes to bring the revised proposal back into review next week (2017-05-23).  Please let me know if you have any questions, thanks!

**Comment by shoamano83** [comment]
Hi @theresalech, I've incorporated the outcome of the follow-up meeting to the proposal and John updated the PR. Please kindly merge this change.
Also, please open up the comment field of https://github.com/smartdevicelink/sdl_evolution/issues/176 so that everybody can add review comments.
Thanks!

**Comment by theresalech** [comment]
@shoamano83 and @jhludwig - it looks like you have two separate pull requests, and two separate files here, one of which is in the incorrect location.  Could you please update your branch and submit a new pull request?  Thank you!

**Comment by jhludwig** [comment]
will, sorry, that was my screw-up

**Pull request merged**
