### PR TITLE
Revise 0314 - Dynamic app list sorting

### PR DESCRIPTION
**Pull request by Akihiro-Miyazaki**
## Introduction
This is an update of SDL-0314.
Change the title name from "Clarification of SDL app icon display sequence and display order" to "Dynamic app list sorting".
Replace the sentence from "the display order of icons" to "to present the dynamic app list sorting methods at the same time".

## Motivation
Replace the sentence from "the sequence and the rules of the SDL app icon display" to "the SDL app icon display sequence and the dynamic app list sorting methods".

## Proposed solution
Modify the "1. Presentation of the dynamic app list sorting methods" according to [this comments(No.2-5)](https://github.com/smartdevicelink/sdl_evolution/issues/1065#issuecomment-673096415)
Replcace the Figure 1 image file to modify the comment of SortList().

## Impact on existing code
Replace the word from "AppHMIType" to "apphmitype_sorting_list".

### CODE REVIEW

**Comment by Akihiro-Miyazaki** [comment]
Hi, @theresalech -san.
This documentation was revised according to [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/1065#issuecomment-673096415).
Could you please review my proposal.
Thank you.

**Comment by theresalech** [comment]
@Akihiro-Miyazaki, since SDL 0314 was withdrawn, if you would like the proposal to be revisited, the first step will be bringing the proposal back under Steering Committee review. The Steering Committee will then need to vote to return the proposal for revisions in order to review a revised version of the proposal.

Can you please advise if you would like SDL 0314 to be brought back under Steering Committee review? I will update https://github.com/smartdevicelink/sdl_evolution/issues/1065 and inform the Steering Committee accordingly. Thank you!

**Comment by Shohei-Kawano** [comment]
@theresalech -san,
I'm sorry. I thought it would be easier to understand if I reconsidered and revised the proposal material and asked the reviewer to see it.
Talking about the fix using the thread can be confusing, so please review it in this Proposal(Markdown file) if possible.
If it is difficult to restart the original Proposal, We would like to close the original Proposal and make a new proposal. Which way should we proceed better?

**Comment by theresalech** [comment]
@Akihiro-Miyazaki , understood. Please close this PR and submit one for a new proposal. See [this section](https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md#making-significant-changes-to-a-proposal) of the Evolution Process document for more information. Thanks!

**Comment by Akihiro-Miyazaki** [comment]
Hi, @theresalech -san,
Thank you for your help.
I understood.
I will close this PR as soon as possible and submit a PR as a new proposal.
Thank you.

**Pull request closed without merging**
