### PR TITLE
SDL-0188 Interior Vehicle Data resumption revision

### PR DESCRIPTION
**Pull request by LuxoftAKutsan**
## Introduction 

Update "SDL-0188 Interior Vehicle Data resumption." The revision is in the scope of fixing typos to match the RPC Spec.

## Motivation

Fix typos to avoid confusion in further activities.

## Proposed solution 

Fix parameter names for GetInteriorVehicleData from `IsSubscribe` to `subscribe` according to the existing API.

In behaviour changes block, replace `SetInteriorVehicleData` with the `GetInteriorVehicleData` RPC that was initially meant.

## Potential downsides 
 N/A

## Impact on existing code
 N/A

## Alternatives considered
 N/A

### CODE REVIEW

**Comment by LuxoftAKutsan** [comment]
@theresalech  please review this proposal revision.
This proposal is intended to be included to 7.0
The revision do not introduce any logical changes to the proposal.
The only fix is types in parameter names and function names.
@yang1070  approved the revision

**Comment by LuxoftAKutsan** [comment]
@theresalech  fixed description. Added paragraphs that were changed

**Comment by theresalech** [comment]
@LuxoftAKutsan, thanks for your updates.  However, the PR description still needs to be changed to match the format of a proposal template, and include _all_ sections (Motivation, Proposed solution, Potential downsides, etc.).  Please see this example: https://github.com/smartdevicelink/sdl_evolution/pull/775.

**Comment by LuxoftAKutsan** [comment]
@theresalech  sorry for confusion. Fixed.

**Comment by LuxoftAKutsan** [comment]
@theresalech  fixed

**Comment by LuxoftAKutsan** [comment]
@theresalech  I added one mode change to the proposal revision. 
There was mentioned that GetInteriorVehicleData should support WARNING result code.
But API changes was not explicitly mentioned.
Commit 6dca09c add this explicit mention

**Comment by theresalech** [comment]
@LuxoftAKutsan, if you would like to see additional changes in the proposed revision, please leave those as a comment on the proposal review issue, here: https://github.com/smartdevicelink/sdl_evolution/issues/1072. This will allow all SDLC members to review and consider in their vote on this revision during our next Steering Committee meeting. Thanks!

**Pull request merged**
