### PR TITLE
iAP over bluetooth support

### PR DESCRIPTION
**Pull request by mghiumiusliu**

### CODE REVIEW

**Comment by mghiumiusliu** [comment]
According request from Robin Kurian - design should be updated.
Therefore changing status of proposal.

**Comment by chinlin0924** [comment]
hello, is this based on iAP1 or iAP2?
regards,
chinlin

**Comment by joeljfischer** [comment]
Is this not the same thing as #158?

**Comment by joeljfischer** [comment]
@mghiumiusliu @theresalech This seems to be the same as the pulled in and deferred proposal. If there's no comments on this, this should be closed.

**Comment by theresalech** [comment]
Closing as duplicate of #158

**Pull request closed without merging**
