### PR TITLE
0091-SDLScreen-SDLWindow-Projection

### PR DESCRIPTION
**Pull request by davidswi**
This PR is a revision to https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0091-SDLScreen-SDLWindow-Projection.md based on changes requested in issue #291.

### CODE REVIEW

**Comment by davidswi** [comment]
This PR is ready for review @theresalech

**Comment by joeygrover** [comment]
@davidswi can you use a proper markdown editor when submitting proposals? The editor you are using is adding  `^M` ( a carriage-return character) instead of the newline value. This makes it very difficult to review as GitHub doesn’t properly stylize them or display them in the code blocks, and when making changes to the original proposal it is impossible to tell what changed without going line by line.

**Comment by davidswi** [comment]
Hi Joey, I am using MacDown. I will check my options.

**Comment by theresalech** [comment]
@davidswi were you able to take a look at the formatting issues here?  It's tough to see the changes you made in the current format, and there appear to be two files here.

**Pull request merged**
