### PR TITLE
Revise SDL-0099 - New remote control modules

### PR DESCRIPTION
**Pull request by joeljfischer**
## Introduction

Remove `GPSLocation` struct and reuse `GPSData`, which as of [SDL-0175](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0175-Updating-DOP-value-range-for-GPS-notification.md) supports optional parameters. Additionally, remove `sRGBColor` struct and reuse `RGBColor` from [SDL-0147](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0147-template-color-scheme.md).

## Motivation

The existing proposal adds duplicate structs.

## Proposed solution

Remove the duplicate structs and reuse `GPSData` and `RGBColor`.

## Potential downsides

None the author could identify.

## Impact on existing code

There will be less duplicated code.

## Alternatives considered

No alternatives were considered.

### CODE REVIEW

**Comment by joeljfischer** [comment]
@theresalech this is ready for review

**Comment by mrapitis** [comment]
@joeljfischer Good suggestion, I also just noticed that two proposals share basically the same rgb color structs.  One used by RC, another used by template improvements, I think it may make sense to include changes to unify these as well?
https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0099-new-remote-control-modules-and-parameters.md
https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0147-template-color-scheme.md

```
<struct name="RGBColor">
    <description>
    </description>
    <param name="red" type="Integer" minValue="0" maxValue="255" mandatory="true" />
    <param name="green" type="Integer" minValue="0" maxValue="255" mandatory="true" />
    <param name="blue" type="Integer" minValue="0" maxValue="255" mandatory="true" />
    </param>
</struct>
```
```
 <struct name="SRGBColor">
    <param name="red" type="Integer" minvalue="0" maxvalue="255"  mandatory="true"/>
    <param name="green" type="Integer" minvalue="0" maxvalue="255"  mandatory="true"/>
    <param name="blue" type="Integer" minvalue="0" maxvalue="255"  mandatory="true"/>
  </struct>
```

**Comment by joeljfischer** [comment]
@mrapitis Yes, those should be unified as well. I'll add that to this proposal.

**Comment by joeljfischer** [comment]
@theresalech I have finished removing duplicate code

**Pull request merged**
