### PR TITLE
Invalid "text" or/and "image" parameters at SoftButton struct of RPC

### PR DESCRIPTION
**Pull request by KhrystynaDubovyk**
Index was added.

### CODE REVIEW

**Comment by KhrystynaDubovyk** [comment]
@mghiumiusliu, @tmelnyk, @sia_drachenko 
Please review

**Comment by asm09fsu** [comment]
@KhrystynaDubovyk this needs to be updated to have a more readable name (don't just put the file name).

**Comment by TMelnyk** [comment]
1. Invalid "text" or/and "image" parameters 
Please change to "Invalid "text" or/and "image" parameters at SoftButton struct of RPC"
2. Required additional clarification from FORD
Please remove
3. Introduction and Motivation are the same
Please update Introdution:
SDL must validate "text" or/and "image" params at SoftButton struct of requested by app RPCs.

**Comment by JackLivio** [comment]
Related PR https://github.com/smartdevicelink/sdl_core/pull/1037

**Comment by mfoedisch** [comment]
So, this is about expecting well-formed parameters even in cases were they are not used, e.g. TEXT Param when SoftButton is of type IMAGE.

I think, this should be handled consistently throughout the whole protocol. If irrelevant params are ignored in other cases, they should also get ignored here and vice versa.

**Comment by joeljfischer** [comment]
@KhrystynaDubovyk @theresalech This has been sitting here for months, can it be closed or marked ready?

**Comment by TMelnyk** [comment]
@KhrystynaDubovyk , please close this PR

**Pull request closed without merging**
