### PR TITLE
Refactor Fuel Information Related Vehicle Data

### PR DESCRIPTION
**Pull request by atiwari9**
In order to partner with more diverse app partners, we need to provide additional sets of vehicle data items through SDL. This goes in line with commitment to enhance SDL with even richer vehicle data content. We need to provide the battery charge level for Electric and Hybrid vehicles to apps that provide navigation, charge station information etc. While we are doing that, we should also work towards making the API leaner and scalable for future demands.

### CODE REVIEW

**Comment by atiwari9** [comment]
@theresalech  - Ready for review

**Comment by theresalech** [comment]
@atiwari9 please submit a PR to make changes to the current file under Steering Committee review (0254-New-vehicle-data-HVBatteryLevel.md) instead of creating a new file.

**Comment by atiwari9** [comment]
@theresalech  - This is the PR to update proposal: https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0254-New-vehicle-data-HVBatteryLevel.md , i had to update the title as well to match the contents of updated proposal. Is it not recommended to change the title of the proposal?

**Comment by theresalech** [comment]
@atiwari9 If you are changing the contents to the point of needing to change the proposal title, we would recommend submitting a new proposal altogether with this new content/title.  Then, the Steering Committee can vote to reject the current proposal in review and bring this new proposal into review instead.

**Comment by atiwari9** [comment]
@theresalech  - I have submitted a new proposal PR, closing this one,

**Pull request closed without merging**
